# This is a basic workflow to help you get started with Actions

name: A1

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

env:
  ATOMCODE: ${${{ github.GITHUB_REPOSITORY }}#${{ github.GITHUB_ACTOR }}/}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: new task added at test
      id: release_step
      run: |
        echo "new task added at test"
        release_time=$(date "+%Y%m%d-%H%M%S")
        echo "::set-output name=release_time::$release_time"
        echo ${{ env.ATOMCODE }}

    # Runs a single command using the runners shell
    - name: 查看文件
      run: ls -l

    # Runs a set of commands using the runners shell
    - name: GITHUB envs
      run: |
        echo "add A1 at dev"
        echo "conflict from main to dev, edit at main"
        echo "edit A1 at dev 333"
        echo "edit A1 at forked main1"
        echo ${{ steps.release_step.outputs.release_time}}
