name: schedule-test-dev
on:
  push:
    branches:
      - '**'
  schedule: 
  - cron:  '*/5 * * * *'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo " this is dev branch"
    - uses: actions/checkout@v2
